#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="analysis_design")]
	public partial class MyDataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBusiness_Owner(Business_Owner instance);
    partial void UpdateBusiness_Owner(Business_Owner instance);
    partial void DeleteBusiness_Owner(Business_Owner instance);
    partial void InsertSystem_Manager(System_Manager instance);
    partial void UpdateSystem_Manager(System_Manager instance);
    partial void DeleteSystem_Manager(System_Manager instance);
    partial void InsertBusiness(Business instance);
    partial void UpdateBusiness(Business instance);
    partial void DeleteBusiness(Business instance);
    partial void InsertBusinesses_of_Business_Owner(Businesses_of_Business_Owner instance);
    partial void UpdateBusinesses_of_Business_Owner(Businesses_of_Business_Owner instance);
    partial void DeleteBusinesses_of_Business_Owner(Businesses_of_Business_Owner instance);
    partial void InsertClient(Client instance);
    partial void UpdateClient(Client instance);
    partial void DeleteClient(Client instance);
    partial void InsertCoupon(Coupon instance);
    partial void UpdateCoupon(Coupon instance);
    partial void DeleteCoupon(Coupon instance);
    partial void InsertCoupons_for_Business(Coupons_for_Business instance);
    partial void UpdateCoupons_for_Business(Coupons_for_Business instance);
    partial void DeleteCoupons_for_Business(Coupons_for_Business instance);
    partial void InsertCoupons_of_Client(Coupons_of_Client instance);
    partial void UpdateCoupons_of_Client(Coupons_of_Client instance);
    partial void DeleteCoupons_of_Client(Coupons_of_Client instance);
    #endregion
		
		public MyDataBaseDataContext() : 
				base(global::DataBase.Properties.Settings.Default.analysis_designConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Business_Owner> Business_Owners
		{
			get
			{
				return this.GetTable<Business_Owner>();
			}
		}
		
		public System.Data.Linq.Table<System_Manager> System_Managers
		{
			get
			{
				return this.GetTable<System_Manager>();
			}
		}
		
		public System.Data.Linq.Table<Business> Businesses
		{
			get
			{
				return this.GetTable<Business>();
			}
		}
		
		public System.Data.Linq.Table<Businesses_of_Business_Owner> Businesses_of_Business_Owners
		{
			get
			{
				return this.GetTable<Businesses_of_Business_Owner>();
			}
		}
		
		public System.Data.Linq.Table<Client> Clients
		{
			get
			{
				return this.GetTable<Client>();
			}
		}
		
		public System.Data.Linq.Table<Coupon> Coupons
		{
			get
			{
				return this.GetTable<Coupon>();
			}
		}
		
		public System.Data.Linq.Table<Coupons_for_Business> Coupons_for_Businesses
		{
			get
			{
				return this.GetTable<Coupons_for_Business>();
			}
		}
		
		public System.Data.Linq.Table<Coupons_of_Client> Coupons_of_Clients
		{
			get
			{
				return this.GetTable<Coupons_of_Client>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Business_Owners")]
	public partial class Business_Owner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _first_name;
		
		private string _last_name;
		
		private string _password;
		
		private System.Nullable<int> _gender;
		
		private string _username;
		
		private System.Nullable<System.DateTime> _birth_date;
		
		private string _email;
		
		private string _phone;
		
		private EntitySet<Businesses_of_Business_Owner> _Businesses_of_Business_Owners;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OngenderChanging(System.Nullable<int> value);
    partial void OngenderChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onbirth_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onbirth_dateChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
		
		public Business_Owner()
		{
			this._Businesses_of_Business_Owners = new EntitySet<Businesses_of_Business_Owner>(new Action<Businesses_of_Business_Owner>(this.attach_Businesses_of_Business_Owners), new Action<Businesses_of_Business_Owner>(this.detach_Businesses_of_Business_Owners));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NChar(10)")]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NChar(10)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(10)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Int")]
		public System.Nullable<int> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth_date", DbType="Date")]
		public System.Nullable<System.DateTime> birth_date
		{
			get
			{
				return this._birth_date;
			}
			set
			{
				if ((this._birth_date != value))
				{
					this.Onbirth_dateChanging(value);
					this.SendPropertyChanging();
					this._birth_date = value;
					this.SendPropertyChanged("birth_date");
					this.Onbirth_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(20)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NChar(10)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Business_Owner_Businesses_of_Business_Owner", Storage="_Businesses_of_Business_Owners", ThisKey="username", OtherKey="Business_Owner")]
		public EntitySet<Businesses_of_Business_Owner> Businesses_of_Business_Owners
		{
			get
			{
				return this._Businesses_of_Business_Owners;
			}
			set
			{
				this._Businesses_of_Business_Owners.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Businesses_of_Business_Owners(Businesses_of_Business_Owner entity)
		{
			this.SendPropertyChanging();
			entity.Business_Owner1 = this;
		}
		
		private void detach_Businesses_of_Business_Owners(Businesses_of_Business_Owner entity)
		{
			this.SendPropertyChanging();
			entity.Business_Owner1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.System_Managers")]
	public partial class System_Manager : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _first_name;
		
		private string _last_name;
		
		private string _password;
		
		private string _username;
		
		private System.Nullable<int> _gender;
		
		private System.Nullable<System.DateTime> _birth_date;
		
		private string _email;
		
		private string _phone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OngenderChanging(System.Nullable<int> value);
    partial void OngenderChanged();
    partial void Onbirth_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onbirth_dateChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
		
		public System_Manager()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NChar(10)")]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NChar(10)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(10)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Int")]
		public System.Nullable<int> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> birth_date
		{
			get
			{
				return this._birth_date;
			}
			set
			{
				if ((this._birth_date != value))
				{
					this.Onbirth_dateChanging(value);
					this.SendPropertyChanging();
					this._birth_date = value;
					this.SendPropertyChanged("birth_date");
					this.Onbirth_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(20)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NChar(10)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Businesses")]
	public partial class Business : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _business_name;
		
		private string _address;
		
		private string _city;
		
		private string _description;
		
		private System.Nullable<int> _category;
		
		private EntityRef<Businesses_of_Business_Owner> _Businesses_of_Business_Owner;
		
		private EntitySet<Coupons_for_Business> _Coupons_for_Businesses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbusiness_nameChanging(string value);
    partial void Onbusiness_nameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OncategoryChanging(System.Nullable<int> value);
    partial void OncategoryChanged();
    #endregion
		
		public Business()
		{
			this._Businesses_of_Business_Owner = default(EntityRef<Businesses_of_Business_Owner>);
			this._Coupons_for_Businesses = new EntitySet<Coupons_for_Business>(new Action<Coupons_for_Business>(this.attach_Coupons_for_Businesses), new Action<Coupons_for_Business>(this.detach_Coupons_for_Businesses));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_business_name", DbType="NChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string business_name
		{
			get
			{
				return this._business_name;
			}
			set
			{
				if ((this._business_name != value))
				{
					this.Onbusiness_nameChanging(value);
					this.SendPropertyChanging();
					this._business_name = value;
					this.SendPropertyChanged("business_name");
					this.Onbusiness_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NChar(30)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NChar(10)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NChar(50)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="Int")]
		public System.Nullable<int> category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Business_Businesses_of_Business_Owner", Storage="_Businesses_of_Business_Owner", ThisKey="business_name", OtherKey="Business", IsUnique=true, IsForeignKey=false)]
		public Businesses_of_Business_Owner Businesses_of_Business_Owner
		{
			get
			{
				return this._Businesses_of_Business_Owner.Entity;
			}
			set
			{
				Businesses_of_Business_Owner previousValue = this._Businesses_of_Business_Owner.Entity;
				if (((previousValue != value) 
							|| (this._Businesses_of_Business_Owner.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Businesses_of_Business_Owner.Entity = null;
						previousValue.Business1 = null;
					}
					this._Businesses_of_Business_Owner.Entity = value;
					if ((value != null))
					{
						value.Business1 = this;
					}
					this.SendPropertyChanged("Businesses_of_Business_Owner");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Business_Coupons_for_Business", Storage="_Coupons_for_Businesses", ThisKey="business_name", OtherKey="Business")]
		public EntitySet<Coupons_for_Business> Coupons_for_Businesses
		{
			get
			{
				return this._Coupons_for_Businesses;
			}
			set
			{
				this._Coupons_for_Businesses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Coupons_for_Businesses(Coupons_for_Business entity)
		{
			this.SendPropertyChanging();
			entity.Business1 = this;
		}
		
		private void detach_Coupons_for_Businesses(Coupons_for_Business entity)
		{
			this.SendPropertyChanging();
			entity.Business1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Businesses_of_Business_Owners")]
	public partial class Businesses_of_Business_Owner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Business_Owner;
		
		private string _Business;
		
		private EntityRef<Business_Owner> _Business_Owner1;
		
		private EntityRef<Business> _Business1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBusiness_OwnerChanging(string value);
    partial void OnBusiness_OwnerChanged();
    partial void OnBusinessChanging(string value);
    partial void OnBusinessChanged();
    #endregion
		
		public Businesses_of_Business_Owner()
		{
			this._Business_Owner1 = default(EntityRef<Business_Owner>);
			this._Business1 = default(EntityRef<Business>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business_Owner", DbType="NChar(10)")]
		public string Business_Owner
		{
			get
			{
				return this._Business_Owner;
			}
			set
			{
				if ((this._Business_Owner != value))
				{
					if (this._Business_Owner1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBusiness_OwnerChanging(value);
					this.SendPropertyChanging();
					this._Business_Owner = value;
					this.SendPropertyChanged("Business_Owner");
					this.OnBusiness_OwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business", DbType="NChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Business
		{
			get
			{
				return this._Business;
			}
			set
			{
				if ((this._Business != value))
				{
					if (this._Business1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBusinessChanging(value);
					this.SendPropertyChanging();
					this._Business = value;
					this.SendPropertyChanged("Business");
					this.OnBusinessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Business_Owner_Businesses_of_Business_Owner", Storage="_Business_Owner1", ThisKey="Business_Owner", OtherKey="username", IsForeignKey=true)]
		public Business_Owner Business_Owner1
		{
			get
			{
				return this._Business_Owner1.Entity;
			}
			set
			{
				Business_Owner previousValue = this._Business_Owner1.Entity;
				if (((previousValue != value) 
							|| (this._Business_Owner1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Business_Owner1.Entity = null;
						previousValue.Businesses_of_Business_Owners.Remove(this);
					}
					this._Business_Owner1.Entity = value;
					if ((value != null))
					{
						value.Businesses_of_Business_Owners.Add(this);
						this._Business_Owner = value.username;
					}
					else
					{
						this._Business_Owner = default(string);
					}
					this.SendPropertyChanged("Business_Owner1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Business_Businesses_of_Business_Owner", Storage="_Business1", ThisKey="Business", OtherKey="business_name", IsForeignKey=true)]
		public Business Business1
		{
			get
			{
				return this._Business1.Entity;
			}
			set
			{
				Business previousValue = this._Business1.Entity;
				if (((previousValue != value) 
							|| (this._Business1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Business1.Entity = null;
						previousValue.Businesses_of_Business_Owner = null;
					}
					this._Business1.Entity = value;
					if ((value != null))
					{
						value.Businesses_of_Business_Owner = this;
						this._Business = value.business_name;
					}
					else
					{
						this._Business = default(string);
					}
					this.SendPropertyChanged("Business1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clients")]
	public partial class Client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _first_name;
		
		private string _last_name;
		
		private string _password;
		
		private System.Nullable<int> _gender;
		
		private string _username;
		
		private System.Nullable<System.DateTime> _birth_day;
		
		private string _email;
		
		private string _phone;
		
		private EntitySet<Coupons_of_Client> _Coupons_of_Clients;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OngenderChanging(System.Nullable<int> value);
    partial void OngenderChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onbirth_dayChanging(System.Nullable<System.DateTime> value);
    partial void Onbirth_dayChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
		
		public Client()
		{
			this._Coupons_of_Clients = new EntitySet<Coupons_of_Client>(new Action<Coupons_of_Client>(this.attach_Coupons_of_Clients), new Action<Coupons_of_Client>(this.detach_Coupons_of_Clients));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NChar(10)")]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NChar(10)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(10)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Int")]
		public System.Nullable<int> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth_day", DbType="DateTime")]
		public System.Nullable<System.DateTime> birth_day
		{
			get
			{
				return this._birth_day;
			}
			set
			{
				if ((this._birth_day != value))
				{
					this.Onbirth_dayChanging(value);
					this.SendPropertyChanging();
					this._birth_day = value;
					this.SendPropertyChanged("birth_day");
					this.Onbirth_dayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(20)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NChar(10)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Client_Coupons_of_Client", Storage="_Coupons_of_Clients", ThisKey="username", OtherKey="Client")]
		public EntitySet<Coupons_of_Client> Coupons_of_Clients
		{
			get
			{
				return this._Coupons_of_Clients;
			}
			set
			{
				this._Coupons_of_Clients.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Coupons_of_Clients(Coupons_of_Client entity)
		{
			this.SendPropertyChanging();
			entity.Client1 = this;
		}
		
		private void detach_Coupons_of_Clients(Coupons_of_Client entity)
		{
			this.SendPropertyChanging();
			entity.Client1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Coupons")]
	public partial class Coupon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _categoryID;
		
		private int _Serial_Number;
		
		private System.Nullable<bool> _isApproved;
		
		private string _name;
		
		private string _description;
		
		private System.Nullable<double> _orginialPrice;
		
		private System.Nullable<double> _discountedPrice;
		
		private System.Nullable<double> _rating;
		
		private System.Nullable<System.DateTime> _lastDate;
		
		private System.Nullable<int> _couponCategory;
		
		private EntitySet<Coupons_for_Business> _Coupons_for_Businesses;
		
		private EntitySet<Coupons_of_Client> _Coupons_of_Clients;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncategoryIDChanging(System.Nullable<int> value);
    partial void OncategoryIDChanged();
    partial void OnSerial_NumberChanging(int value);
    partial void OnSerial_NumberChanged();
    partial void OnisApprovedChanging(System.Nullable<bool> value);
    partial void OnisApprovedChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnorginialPriceChanging(System.Nullable<double> value);
    partial void OnorginialPriceChanged();
    partial void OndiscountedPriceChanging(System.Nullable<double> value);
    partial void OndiscountedPriceChanged();
    partial void OnratingChanging(System.Nullable<double> value);
    partial void OnratingChanged();
    partial void OnlastDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastDateChanged();
    partial void OncouponCategoryChanging(System.Nullable<int> value);
    partial void OncouponCategoryChanged();
    #endregion
		
		public Coupon()
		{
			this._Coupons_for_Businesses = new EntitySet<Coupons_for_Business>(new Action<Coupons_for_Business>(this.attach_Coupons_for_Businesses), new Action<Coupons_for_Business>(this.detach_Coupons_for_Businesses));
			this._Coupons_of_Clients = new EntitySet<Coupons_of_Client>(new Action<Coupons_of_Client>(this.attach_Coupons_of_Clients), new Action<Coupons_of_Client>(this.detach_Coupons_of_Clients));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoryID", DbType="Int")]
		public System.Nullable<int> categoryID
		{
			get
			{
				return this._categoryID;
			}
			set
			{
				if ((this._categoryID != value))
				{
					this.OncategoryIDChanging(value);
					this.SendPropertyChanging();
					this._categoryID = value;
					this.SendPropertyChanged("categoryID");
					this.OncategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serial_Number", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Serial_Number
		{
			get
			{
				return this._Serial_Number;
			}
			set
			{
				if ((this._Serial_Number != value))
				{
					this.OnSerial_NumberChanging(value);
					this.SendPropertyChanging();
					this._Serial_Number = value;
					this.SendPropertyChanged("Serial_Number");
					this.OnSerial_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isApproved", DbType="Bit")]
		public System.Nullable<bool> isApproved
		{
			get
			{
				return this._isApproved;
			}
			set
			{
				if ((this._isApproved != value))
				{
					this.OnisApprovedChanging(value);
					this.SendPropertyChanging();
					this._isApproved = value;
					this.SendPropertyChanged("isApproved");
					this.OnisApprovedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(10)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NChar(50)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orginialPrice", DbType="Float")]
		public System.Nullable<double> orginialPrice
		{
			get
			{
				return this._orginialPrice;
			}
			set
			{
				if ((this._orginialPrice != value))
				{
					this.OnorginialPriceChanging(value);
					this.SendPropertyChanging();
					this._orginialPrice = value;
					this.SendPropertyChanged("orginialPrice");
					this.OnorginialPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discountedPrice", DbType="Float")]
		public System.Nullable<double> discountedPrice
		{
			get
			{
				return this._discountedPrice;
			}
			set
			{
				if ((this._discountedPrice != value))
				{
					this.OndiscountedPriceChanging(value);
					this.SendPropertyChanging();
					this._discountedPrice = value;
					this.SendPropertyChanged("discountedPrice");
					this.OndiscountedPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rating", DbType="Float")]
		public System.Nullable<double> rating
		{
			get
			{
				return this._rating;
			}
			set
			{
				if ((this._rating != value))
				{
					this.OnratingChanging(value);
					this.SendPropertyChanging();
					this._rating = value;
					this.SendPropertyChanged("rating");
					this.OnratingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastDate
		{
			get
			{
				return this._lastDate;
			}
			set
			{
				if ((this._lastDate != value))
				{
					this.OnlastDateChanging(value);
					this.SendPropertyChanging();
					this._lastDate = value;
					this.SendPropertyChanged("lastDate");
					this.OnlastDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_couponCategory", DbType="Int")]
		public System.Nullable<int> couponCategory
		{
			get
			{
				return this._couponCategory;
			}
			set
			{
				if ((this._couponCategory != value))
				{
					this.OncouponCategoryChanging(value);
					this.SendPropertyChanging();
					this._couponCategory = value;
					this.SendPropertyChanged("couponCategory");
					this.OncouponCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Coupon_Coupons_for_Business", Storage="_Coupons_for_Businesses", ThisKey="Serial_Number", OtherKey="Coupon")]
		public EntitySet<Coupons_for_Business> Coupons_for_Businesses
		{
			get
			{
				return this._Coupons_for_Businesses;
			}
			set
			{
				this._Coupons_for_Businesses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Coupon_Coupons_of_Client", Storage="_Coupons_of_Clients", ThisKey="Serial_Number", OtherKey="Coupon_Serial_Number")]
		public EntitySet<Coupons_of_Client> Coupons_of_Clients
		{
			get
			{
				return this._Coupons_of_Clients;
			}
			set
			{
				this._Coupons_of_Clients.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Coupons_for_Businesses(Coupons_for_Business entity)
		{
			this.SendPropertyChanging();
			entity.Coupon1 = this;
		}
		
		private void detach_Coupons_for_Businesses(Coupons_for_Business entity)
		{
			this.SendPropertyChanging();
			entity.Coupon1 = null;
		}
		
		private void attach_Coupons_of_Clients(Coupons_of_Client entity)
		{
			this.SendPropertyChanging();
			entity.Coupon = this;
		}
		
		private void detach_Coupons_of_Clients(Coupons_of_Client entity)
		{
			this.SendPropertyChanging();
			entity.Coupon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Coupons_for_Businesses")]
	public partial class Coupons_for_Business : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Business;
		
		private int _Coupon;
		
		private EntityRef<Business> _Business1;
		
		private EntityRef<Coupon> _Coupon1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBusinessChanging(string value);
    partial void OnBusinessChanged();
    partial void OnCouponChanging(int value);
    partial void OnCouponChanged();
    #endregion
		
		public Coupons_for_Business()
		{
			this._Business1 = default(EntityRef<Business>);
			this._Coupon1 = default(EntityRef<Coupon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business", DbType="NChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Business
		{
			get
			{
				return this._Business;
			}
			set
			{
				if ((this._Business != value))
				{
					if (this._Business1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBusinessChanging(value);
					this.SendPropertyChanging();
					this._Business = value;
					this.SendPropertyChanged("Business");
					this.OnBusinessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Coupon
		{
			get
			{
				return this._Coupon;
			}
			set
			{
				if ((this._Coupon != value))
				{
					if (this._Coupon1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCouponChanging(value);
					this.SendPropertyChanging();
					this._Coupon = value;
					this.SendPropertyChanged("Coupon");
					this.OnCouponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Business_Coupons_for_Business", Storage="_Business1", ThisKey="Business", OtherKey="business_name", IsForeignKey=true)]
		public Business Business1
		{
			get
			{
				return this._Business1.Entity;
			}
			set
			{
				Business previousValue = this._Business1.Entity;
				if (((previousValue != value) 
							|| (this._Business1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Business1.Entity = null;
						previousValue.Coupons_for_Businesses.Remove(this);
					}
					this._Business1.Entity = value;
					if ((value != null))
					{
						value.Coupons_for_Businesses.Add(this);
						this._Business = value.business_name;
					}
					else
					{
						this._Business = default(string);
					}
					this.SendPropertyChanged("Business1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Coupon_Coupons_for_Business", Storage="_Coupon1", ThisKey="Coupon", OtherKey="Serial_Number", IsForeignKey=true)]
		public Coupon Coupon1
		{
			get
			{
				return this._Coupon1.Entity;
			}
			set
			{
				Coupon previousValue = this._Coupon1.Entity;
				if (((previousValue != value) 
							|| (this._Coupon1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Coupon1.Entity = null;
						previousValue.Coupons_for_Businesses.Remove(this);
					}
					this._Coupon1.Entity = value;
					if ((value != null))
					{
						value.Coupons_for_Businesses.Add(this);
						this._Coupon = value.Serial_Number;
					}
					else
					{
						this._Coupon = default(int);
					}
					this.SendPropertyChanged("Coupon1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Coupons_of_Clients")]
	public partial class Coupons_of_Client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Client;
		
		private int _Coupon_Serial_Number;
		
		private EntityRef<Client> _Client1;
		
		private EntityRef<Coupon> _Coupon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClientChanging(string value);
    partial void OnClientChanged();
    partial void OnCoupon_Serial_NumberChanging(int value);
    partial void OnCoupon_Serial_NumberChanged();
    #endregion
		
		public Coupons_of_Client()
		{
			this._Client1 = default(EntityRef<Client>);
			this._Coupon = default(EntityRef<Coupon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					if (this._Client1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClientChanging(value);
					this.SendPropertyChanging();
					this._Client = value;
					this.SendPropertyChanged("Client");
					this.OnClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_Serial_Number", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Coupon_Serial_Number
		{
			get
			{
				return this._Coupon_Serial_Number;
			}
			set
			{
				if ((this._Coupon_Serial_Number != value))
				{
					if (this._Coupon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCoupon_Serial_NumberChanging(value);
					this.SendPropertyChanging();
					this._Coupon_Serial_Number = value;
					this.SendPropertyChanged("Coupon_Serial_Number");
					this.OnCoupon_Serial_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Client_Coupons_of_Client", Storage="_Client1", ThisKey="Client", OtherKey="username", IsForeignKey=true)]
		public Client Client1
		{
			get
			{
				return this._Client1.Entity;
			}
			set
			{
				Client previousValue = this._Client1.Entity;
				if (((previousValue != value) 
							|| (this._Client1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Client1.Entity = null;
						previousValue.Coupons_of_Clients.Remove(this);
					}
					this._Client1.Entity = value;
					if ((value != null))
					{
						value.Coupons_of_Clients.Add(this);
						this._Client = value.username;
					}
					else
					{
						this._Client = default(string);
					}
					this.SendPropertyChanged("Client1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Coupon_Coupons_of_Client", Storage="_Coupon", ThisKey="Coupon_Serial_Number", OtherKey="Serial_Number", IsForeignKey=true)]
		public Coupon Coupon
		{
			get
			{
				return this._Coupon.Entity;
			}
			set
			{
				Coupon previousValue = this._Coupon.Entity;
				if (((previousValue != value) 
							|| (this._Coupon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Coupon.Entity = null;
						previousValue.Coupons_of_Clients.Remove(this);
					}
					this._Coupon.Entity = value;
					if ((value != null))
					{
						value.Coupons_of_Clients.Add(this);
						this._Coupon_Serial_Number = value.Serial_Number;
					}
					else
					{
						this._Coupon_Serial_Number = default(int);
					}
					this.SendPropertyChanged("Coupon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
